server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|svg|woff2?|ttf|eot|ico|png|jpg|jpeg|gif)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public";
    }
}
