import { Analysis, Site, TeamMember } from "../types/domain";

export const initialSites: Site[] = [
  { id: "site-1", name: "Marketing site", url: "https://example.com" },
  { id: "site-2", name: "Customer portal", url: "https://app.example.com" },
  { id: "site-3", name: "Documentation", url: "https://docs.example.com" },
];

export const initialMembers: TeamMember[] = [
  { id: "member-1", email: "owner@example.com", role: "Owner" },
  { id: "member-2", email: "security@example.com", role: "Member" },
];

export const initialAnalyses: Analysis[] = [
  {
    id: "analysis-42",
    siteId: "site-1",
    siteName: "Marketing site",
    url: "https://example.com",
    createdAt: "May 21, 2026 10:40",
    status: "Completed",
    selectedScans: ["crawl", "https", "headers", "adminPaths", "sensitiveFiles"],
    crawlDepth: 3,
    includeSubdomains: false,
    findings: [
      {
        id: "F-104",
        title: "Content Security Policy is missing",
        severity: "High",
        status: "Open",
        affected: "https://example.com/",
        summary: "The browser is not receiving a policy that limits which scripts and assets can run on the page.",
        impact: "If another bug allows script injection, attackers could more easily steal sessions or alter what users see.",
        check: "Security headers",
      },
      {
        id: "F-118",
        title: "Public admin path detected",
        severity: "Medium",
        status: "Open",
        affected: "https://example.com/admin",
        summary: "A commonly guessed admin route responds publicly and can be discovered without authentication.",
        impact: "Attackers get a clear target for password attacks and software fingerprinting.",
        check: "Exposed routes",
      },
      {
        id: "F-126",
        title: "Source map is publicly reachable",
        severity: "Low",
        status: "Open",
        affected: "https://example.com/assets/app.js.map",
        summary: "A bundled source map is available to visitors and may reveal frontend source structure.",
        impact: "Internal implementation details become easier to inspect during reconnaissance.",
        check: "Sensitive files",
      },
    ],
  },
  {
    id: "analysis-41",
    siteId: "site-2",
    siteName: "Customer portal",
    url: "https://app.example.com",
    createdAt: "May 20, 2026 16:15",
    status: "Completed",
    selectedScans: ["crawl", "https", "headers", "secrets"],
    crawlDepth: 2,
    includeSubdomains: true,
    findings: [
      {
        id: "F-090",
        title: "API key pattern found in JavaScript bundle",
        severity: "Critical",
        status: "Open",
        affected: "https://app.example.com/assets/dashboard.js",
        summary: "A token-like value appears in a public client-side bundle and should be reviewed.",
        impact: "A real credential could allow unauthorized access to internal APIs or third-party services.",
        check: "Client bundle secrets",
      },
      {
        id: "F-091",
        title: "Referrer-Policy header is missing",
        severity: "Low",
        status: "Fixed",
        affected: "https://app.example.com/",
        summary: "The site does not control how much referrer information browsers send to other origins.",
        impact: "Private URL paths or query parameters may leak to external services.",
        check: "Security headers",
        reason: "Header added in the frontend ingress config.",
      },
    ],
  },
  {
    id: "analysis-40",
    siteId: "site-3",
    siteName: "Documentation",
    url: "https://docs.example.com",
    createdAt: "May 19, 2026 09:05",
    status: "Completed",
    selectedScans: ["crawl", "https", "sensitiveFiles"],
    crawlDepth: 1,
    includeSubdomains: false,
    findings: [
      {
        id: "F-071",
        title: "HSTS is enabled",
        severity: "Info",
        status: "Open",
        affected: "https://docs.example.com/",
        summary: "The site tells browsers to keep using encrypted connections on future visits.",
        impact: "This reduces the chance of users being downgraded to an unencrypted session.",
        check: "HTTPS",
      },
    ],
  },
];
