/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check auth service liveness */
        get: operations["getAuthHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset link
         * @description Always returns `200` with the same message whether or not the email is
         *     registered, so this endpoint cannot be used to enumerate accounts. If the
         *     email is registered, a single-use reset token is generated and emailed to it.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a reset token for a new password */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's registered websites */
        get: operations["listWebsites"];
        put?: never;
        /** Register a website for scanning */
        post: operations["createWebsite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{websiteId}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a website registered by the authenticated user. */
                websiteId: components["parameters"]["WebsiteId"];
            };
            cookie?: never;
        };
        /** List the scan history of a website */
        get: operations["listScans"];
        put?: never;
        /**
         * Trigger a new scan for a website
         * @description Creates the scan in status `Pending` and returns immediately; execution
         *     happens in the background. At most one scan per website may be
         *     `Pending` or `Running` at a time — a second trigger returns `409`.
         */
        post: operations["triggerScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{websiteId}/scans/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the most recent scan of a website */
        get: operations["getLatestScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return a scan's current status
         * @description Poll this endpoint while the status is `Pending` or `Running`.
         */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the findings of a scan
         * @description Empty until the scan status is `Completed`.
         */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun a scan using the same configuration
         * @description Creates a new Pending scan for the same website and scan configuration as the selected scan.
         */
        post: operations["rescan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare this scan with the previous completed scan
         * @description Compares the selected completed scan with the latest previous completed scan for the same website.
         */
        get: operations["getScanComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/report/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return computed report data for a scan
         * @description Includes prioritized findings, rough effort estimates, recommended next steps, and the safe-to-launch checklist.
         */
        get: operations["getScanReportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/report/summary.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export an executive summary as HTML */
        get: operations["exportExecutiveSummaryHtml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/report/summary.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export an executive summary as PDF */
        get: operations["exportExecutiveSummaryPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/report/full.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the full scan results as PDF */
        get: operations["exportFullScanReportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Unified error shape returned by every VibeShield service. */
        Error: {
            /**
             * @description Stable machine-readable error code, e.g. `SCAN_IN_PROGRESS`.
             * @example SCAN_IN_PROGRESS
             */
            code: string;
            /**
             * @description Human-readable explanation.
             * @example A scan for this website is already running.
             */
            message: string;
            /** @description Optional structured context (e.g. field-level validation errors). */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        MessageResponse: {
            /** @example User registered successfully */
            message: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example vibecoder@example.org
             */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            /** @description JWT to send as `Authorization: Bearer <token>`. */
            token: string;
            /** Format: email */
            email: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            /** @description Single-use reset token from the forgot-password email. */
            token: string;
            /** Format: password */
            newPassword: string;
        };
        UserResponse: {
            /** Format: email */
            email: string;
        };
        Website: {
            /**
             * Format: int64
             * @example 7
             */
            id: number;
            /**
             * Format: uri
             * @example https://my-vibecoded-shop.lovable.app
             */
            url: string;
            /**
             * @description Display name; defaults to the URL host when not provided.
             * @example My shop
             */
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateWebsiteRequest: {
            /**
             * Format: uri
             * @description Must be an absolute http(s) URL.
             * @example https://my-vibecoded-shop.lovable.app
             */
            url: string;
            /** @description Optional display name; defaults to the URL host. */
            name?: string;
        };
        /** @description Configuration for a scan run. All fields are optional. */
        ScanRequest: {
            /** @description Checks to run; defaults to all available checks. */
            checks?: components["schemas"]["ScanCheck"][];
            /** @description How many link levels to follow from the start URL. Defaults to 0, which scans only the registered URL. */
            crawlDepth?: number;
            /** @description Whether the crawl may follow links to subdomains of the registered host. Defaults to false. */
            includeSubdomains?: boolean;
        };
        /** @description A scan job and its current state. */
        Scan: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /**
             * Format: int64
             * @example 7
             */
            websiteId: number;
            status: components["schemas"]["ScanStatus"];
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Set once the status is `Completed` or `Failed`.
             */
            completedAt?: string | null;
            /** @description Why the scan failed; only set when the status is `Failed`. */
            errorMessage?: string | null;
            /**
             * @description Number of findings; only set when the status is `Completed`.
             * @example 5
             */
            findingCount?: number | null;
        };
        /**
         * @description Lifecycle of a scan job.
         * @enum {string}
         */
        ScanStatus: "Pending" | "Running" | "Completed" | "Failed";
        /**
         * @description A surface-level check the scanner can run. Values match the scan
         *     options offered in the client UI.
         * @enum {string}
         */
        ScanCheck: "crawl" | "https" | "headers" | "adminPaths" | "secrets" | "sensitiveFiles" | "cookies";
        /**
         * @description How urgently a finding should be fixed.
         * @enum {string}
         */
        Severity: "Critical" | "High" | "Medium" | "Low" | "Info";
        /**
         * @description Triage state of a finding. New findings start as `Open`.
         * @enum {string}
         */
        FindingStatus: "Open" | "Fixed" | "Ignored";
        /** @description A single security issue discovered by a scan. */
        Finding: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            scanId: number;
            check: components["schemas"]["ScanCheck"];
            /** @example Missing Content-Security-Policy header */
            title: string;
            severity: components["schemas"]["Severity"];
            /**
             * @description URL, path, or header the finding applies to.
             * @example https://my-vibecoded-shop.lovable.app/
             */
            affected: string;
            /** @description Non-technical explanation of the risk, written for vibecoders. */
            explanation: string;
            /** @description Plain-language fix suggestion; input for AI fix-prompt generation. */
            suggestedFix: string;
            status: components["schemas"]["FindingStatus"];
        };
        /**
         * @description How a finding changed compared with the previous completed scan.
         * @enum {string}
         */
        ScanChangeStatus: "Fixed" | "Still present" | "Newly introduced";
        ComparisonFinding: {
            /**
             * Format: int64
             * @description ID of the finding in the scan it came from.
             */
            findingId?: number | null;
            changeStatus: components["schemas"]["ScanChangeStatus"];
            severity: components["schemas"]["Severity"];
            check: components["schemas"]["ScanCheck"];
            title: string;
            affected: string;
            suggestedFix: string;
            /** @description 1-based action-plan order for current open findings. */
            suggestedFixOrder?: number | null;
            effort: components["schemas"]["EffortEstimate"];
        };
        ScanComparisonSummary: {
            fixed: number;
            stillPresent: number;
            newlyIntroduced: number;
        };
        ScanComparison: {
            /** Format: int64 */
            scanId: number;
            /** Format: int64 */
            previousScanId?: number | null;
            /** @description False when the scan is not completed or no previous completed scan exists. */
            comparable: boolean;
            message: string;
            summary: components["schemas"]["ScanComparisonSummary"];
            /** @description Fixed, still-present, and newly introduced findings. */
            findings: components["schemas"]["ComparisonFinding"][];
            /** @description Current open findings ordered by severity and rough effort estimate. */
            actionPlan: components["schemas"]["ComparisonFinding"][];
        };
        EffortEstimate: {
            /** @enum {string} */
            level: "Low" | "Medium" | "High";
            /** @example 1-2 hours */
            estimate: string;
        };
        ReportSite: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: uri */
            url: string;
        };
        ReportFinding: {
            /** Format: int64 */
            id: number;
            severity: components["schemas"]["Severity"];
            check: components["schemas"]["ScanCheck"];
            title: string;
            affected: string;
            explanation: string;
            suggestedFix: string;
            status: components["schemas"]["FindingStatus"];
            /** @description 1-based priority among open findings; null for fixed or ignored findings. */
            suggestedFixOrder?: number | null;
            effort: components["schemas"]["EffortEstimate"];
        };
        ReportNextStep: {
            order: number;
            title: string;
            severity: components["schemas"]["Severity"];
            affected: string;
            effort: components["schemas"]["EffortEstimate"];
            action: string;
        };
        LaunchChecklistItem: {
            /** @example HTTPS and mixed-content checks */
            label: string;
            /**
             * @description Launch-readiness result for this scan category.
             * @enum {string}
             */
            result: "Pass" | "Needs attention" | "Not selected" | "Incomplete";
            /** @description Whether this scan category was selected and evaluated. */
            checked: boolean;
            /** @example Checked and found 1 open finding; highest severity is High. */
            reason: string;
        };
        LaunchChecklist: {
            /** @enum {string} */
            status: "Safe to launch" | "Safe with warnings" | "Needs attention" | "Not safe to launch";
            blockingIssues: number;
            items: components["schemas"]["LaunchChecklistItem"][];
        };
        ExecutiveSummary: {
            /** @enum {string} */
            riskLevel: "Critical" | "High" | "Medium" | "Low";
            totalFindings: number;
            openFindings: number;
            recommendedNextSteps: components["schemas"]["ReportNextStep"][];
        };
        ReportData: {
            /** Format: int64 */
            scanId: number;
            site: components["schemas"]["ReportSite"];
            scanStatus: components["schemas"]["ScanStatus"];
            /** Format: date-time */
            scanCreatedAt: string;
            /** Format: date-time */
            scanCompletedAt?: string | null;
            /** Format: date-time */
            generatedAt: string;
            safeToLaunch: components["schemas"]["LaunchChecklist"];
            executiveSummary: components["schemas"]["ExecutiveSummary"];
            findings: components["schemas"]["ReportFinding"][];
        };
    };
    responses: {
        /** @description Missing, expired, or invalid Bearer token (`UNAUTHORIZED`, `INVALID_TOKEN`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist or belongs to another user (`WEBSITE_NOT_FOUND`, `SCAN_NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description ID of a website registered by the authenticated user. */
        WebsiteId: number;
        /** @description ID of a scan belonging to one of the user's websites. */
        ScanId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth service is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid input or email already registered (`EMAIL_ALREADY_REGISTERED`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; send the token as `Authorization: Bearer <token>`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Bad credentials (`INVALID_CREDENTIALS`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Request accepted; a reset email was sent if the address is registered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Token is missing, unknown, expired, or already used (`INVALID_RESET_TOKEN`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user the presented token belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listWebsites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All websites registered by the user, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Website"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebsite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebsiteRequest"];
            };
        };
        responses: {
            /** @description Website registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Website"];
                };
            };
            /** @description URL is missing or not a valid http(s) URL (`VALIDATION_ERROR`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The user already registered this URL (`WEBSITE_ALREADY_REGISTERED`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listScans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a website registered by the authenticated user. */
                websiteId: components["parameters"]["WebsiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All scans for the website, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    triggerScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a website registered by the authenticated user. */
                websiteId: components["parameters"]["WebsiteId"];
            };
            cookie?: never;
        };
        /** @description Optional scan configuration; omitting it runs all checks with defaults. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Scan accepted for background execution. */
            202: {
                headers: {
                    /** @description URL of the created scan, for status polling. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description A scan for this website is already `Pending` or `Running` (`SCAN_IN_PROGRESS`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLatestScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a website registered by the authenticated user. */
                websiteId: components["parameters"]["WebsiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most recently created scan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Website not visible to this user, or it has no scans yet (`SCAN_NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current scan state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listFindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Findings ordered by severity, most severe first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    rescan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rescan accepted for background execution. */
            202: {
                headers: {
                    /** @description URL of the created scan, for status polling. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description A scan for this website is already `Pending` or `Running` (`SCAN_IN_PROGRESS`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScanComparison: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comparison result and prioritized action plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanComparison"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getScanReportData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computed report data for the current scan state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportData"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportExecutiveSummaryHtml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloadable executive summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportExecutiveSummaryPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloadable executive summary PDF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportFullScanReportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of a scan belonging to one of the user's websites. */
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloadable full scan results PDF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
