apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner-service
  template:
    metadata:
      labels:
        app: scanner-service
    spec:
      containers:
        - name: scanner-service
          image: ghcr.io/aet-devops26/team-hallucination-detectors-scanner-service:latest
          ports:
            - containerPort: 8080
